// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ussrxvmbtktztiefcnqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzc3J4dm1idGt0enRpZWZjbnFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjk1NDMsImV4cCI6MjA2Mzg0NTU0M30.jKjnTzRBI5SmTFo7C4FW43MvgQFXgYpw6VwkQxWwL5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);